repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
     - id: trailing-whitespace
     - id: end-of-file-fixer
     - id: check-yaml
     - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    - id: black

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
     - id: pyupgrade
