# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 09:32
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(null=True)),
                ('body', models.TextField(null=True)),
                ('title_i18n', django.contrib.postgres.fields.jsonb.JSONField()),
                ('body_i18n', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
