# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 10:37
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='body_i18n',
            field=django.contrib.postgres.fields.jsonb.JSONField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title_i18n',
            field=django.contrib.postgres.fields.jsonb.JSONField(editable=False, null=True),
        ),
    ]
