# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 13:52
from __future__ import unicode_literals

from django.db import migrations
import modeltrans.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AddField(
            model_name='blog',
            name='i18n',
            field=modeltrans.fields.TranslationJSONField(),
        ),
        migrations.AddField(
            model_name='category',
            name='i18n',
            field=modeltrans.fields.TranslationJSONField(),
        ),
    ]
