# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 09:07
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170407_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='body_i18n',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='title_i18n',
        ),
        migrations.AddField(
            model_name='blog',
            name='i18n',
            field=django.contrib.postgres.fields.jsonb.JSONField(editable=False, null=True),
        ),
    ]
